apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<region>.amazonaws.com/myapp:v1
        env:
        - name: DB_HOST
          value: "my-database"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "password123"
        - name: DB_NAME
          value: "myappdb"
        ports:
        - containerPort: 5000
